/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Admin;
import model.Car;


/**
 *
 * @author Eva
 */
public class UpdateCarJPanel extends javax.swing.JPanel {
    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
    Date date = new Date();
    Calendar calender = Calendar.getInstance();

    /**
     * Creates new form UpdateCarJPanel
     */
    private JPanel workAreaJPanel;
    private Car car;
    private Admin admin;
    


    
    public UpdateCarJPanel(JPanel wajp, Car c, Admin a) {
        initComponents();
        setSize(600,600);
        workAreaJPanel = wajp;
        car = c;
        admin = a;
        
        cmbCarModel.setModel(new DefaultComboBoxModel<>(new String[]{
            "X","XL","XXL"
        }));
        
        cmbCarSeat.setModel(new DefaultComboBoxModel<>(new String[]{
            "5","7","9"
        }));
        
        cmbIsAvail.setModel(new DefaultComboBoxModel<>(new String[]{
            "Yes","No"
        }));
        
        cmbIsExpired.setModel(new DefaultComboBoxModel<>(new String[]{
            "Yes","No"
        }));
        
        txtCarName.setText(c.getCarName());
        txtCarBrand.setText(c.getCarBrand());
        cmbCarModel.setSelectedItem(c.getCarModel());
        txtCarCity.setText(c.getCarCity());
        cmbCarSeat.setSelectedItem(c.getCarSeat());
        txtCarYear.setText(c.getCarYear());
        cmbIsAvail.setSelectedItem(c.getIsAvail());
        cmbIsExpired.setSelectedItem(c.getIsExpired());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIsAvail = new javax.swing.JLabel();
        lblCarBrand = new javax.swing.JLabel();
        cmbIsAvail = new javax.swing.JComboBox<>();
        txtCarBrand = new javax.swing.JTextField();
        lblIsExpired = new javax.swing.JLabel();
        lblCarModel = new javax.swing.JLabel();
        cmbIsExpired = new javax.swing.JComboBox<>();
        cmbCarModel = new javax.swing.JComboBox<>();
        btnConfirmAdd = new javax.swing.JButton();
        lblCarCity = new javax.swing.JLabel();
        txtCarCity = new javax.swing.JTextField();
        lblCarSeat = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        cmbCarSeat = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        lblCarYear = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        txtCarYear = new javax.swing.JTextField();
        txtCarName = new javax.swing.JTextField();

        lblIsAvail.setText("Is Available?");

        lblCarBrand.setText("Car Brand:");

        cmbIsAvail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIsAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIsAvailActionPerformed(evt);
            }
        });

        lblIsExpired.setText("Is Expired?");

        lblCarModel.setText("Car Model:");

        cmbIsExpired.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCarModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnConfirmAdd.setText("Confirm Update");
        btnConfirmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddActionPerformed(evt);
            }
        });

        lblCarCity.setText("Car City:");

        lblCarSeat.setText("Seats Number:");

        lblTitle.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Car");

        cmbCarSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCarYear.setText("Production Year:");

        lblCarName.setText("Car Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnConfirmAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(249, 249, 249))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCarYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIsAvail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIsExpired, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(12, 12, 12))
                                            .addComponent(lblCarSeat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCarBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblCarModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(36, 36, 36)))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCarCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(105, 105, 105))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbCarSeat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCarYear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCarModel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbIsAvail, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbIsExpired, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCarCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarBrand, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCarName, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(178, 178, 178))
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarName)
                    .addComponent(txtCarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarBrand)
                    .addComponent(txtCarBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarModel)
                    .addComponent(cmbCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarCity)
                    .addComponent(txtCarCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCarSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarSeat))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarYear)
                    .addComponent(txtCarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsAvail)
                    .addComponent(cmbIsAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsExpired)
                    .addComponent(cmbIsExpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnConfirmAdd)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIsAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIsAvailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIsAvailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void backAction() {
        workAreaJPanel.remove(this);
        Component[] componentArray = workAreaJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageJPanel manageJPanel = (ManageJPanel) component;
        manageJPanel.refreshTable();
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }
    
    
    
    
    private void btnConfirmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddActionPerformed
        // TODO add your handling code here:
        if(txtCarName.getText().equals("")||txtCarBrand.getText().equals("")||txtCarCity.getText().equals("")||txtCarYear.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Please enter all information!", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }else{
            

        car.setCarName(txtCarName.getText());
        car.setCarBrand(txtCarBrand.getText());
        car.setCarModel(cmbCarModel.getSelectedItem().toString());
        car.setCarCity(txtCarCity.getText());
        car.setCarSeat(cmbCarSeat.getSelectedItem().toString());
        car.setCarYear(txtCarYear.getText());
        car.setIsAvail(cmbIsAvail.getSelectedItem().toString());
        car.setIsExpired(cmbIsExpired.getSelectedItem().toString());
        car.setTime(dateFormat.format(date));
        
        JOptionPane.showMessageDialog(this, "Car updated");
        System.out.println(dateFormat.format(date));
       
        
        
        
        
        
        
            
        
        }
    }//GEN-LAST:event_btnConfirmAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmAdd;
    private javax.swing.JComboBox<String> cmbCarModel;
    private javax.swing.JComboBox<String> cmbCarSeat;
    private javax.swing.JComboBox<String> cmbIsAvail;
    private javax.swing.JComboBox<String> cmbIsExpired;
    private javax.swing.JLabel lblCarBrand;
    private javax.swing.JLabel lblCarCity;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCarSeat;
    private javax.swing.JLabel lblCarYear;
    private javax.swing.JLabel lblIsAvail;
    private javax.swing.JLabel lblIsExpired;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCarBrand;
    private javax.swing.JTextField txtCarCity;
    private javax.swing.JTextField txtCarName;
    private javax.swing.JTextField txtCarYear;
    // End of variables declaration//GEN-END:variables
}
