/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.manage;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Encounter;
import model.Patient;

/**
 *
 * @author Eva
 */
public class UpdateEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateEncounter
     */
    
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    Date date = new Date();
    Calendar calender = Calendar.getInstance();
    
    JPanel workAreaJPanel;
    Patient patient;
    Encounter encounter;
    
    
    public UpdateEncounterJPanel(JPanel wajp, Encounter e, Patient p) {
        initComponents();
        setSize(600,600);
        workAreaJPanel =wajp;
        patient = p;
        encounter =e ;
        
        txtSystolicPressure.setText(Integer.toString(e.getSystolicPressure()));
        txtDiastolicPressure.setText(Integer.toString(e.getDiastolicPressure()));  
  
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmAdd = new javax.swing.JButton();
        txtSystolicPressure = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtDiastolicPressure = new javax.swing.JTextField();
        lblSPValid = new javax.swing.JLabel();
        lblDPValid = new javax.swing.JLabel();
        lblDiastolicPressure = new javax.swing.JLabel();
        lblSystolicPressure = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnConfirmAdd.setBackground(new java.awt.Color(0, 51, 204));
        btnConfirmAdd.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnConfirmAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmAdd.setText("Confirm Update");
        btnConfirmAdd.setBorderPainted(false);
        btnConfirmAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAddActionPerformed(evt);
            }
        });

        txtSystolicPressure.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        txtSystolicPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSystolicPressureActionPerformed(evt);
            }
        });
        txtSystolicPressure.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSystolicPressureKeyReleased(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Encounter");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtDiastolicPressure.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        txtDiastolicPressure.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiastolicPressureKeyReleased(evt);
            }
        });

        lblSPValid.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblSPValid.setForeground(new java.awt.Color(51, 51, 51));
        lblSPValid.setMaximumSize(new java.awt.Dimension(42, 23));
        lblSPValid.setMinimumSize(new java.awt.Dimension(42, 23));

        lblDPValid.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lblDPValid.setForeground(new java.awt.Color(51, 51, 51));
        lblDPValid.setMaximumSize(new java.awt.Dimension(42, 23));
        lblDPValid.setMinimumSize(new java.awt.Dimension(42, 23));

        lblDiastolicPressure.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblDiastolicPressure.setText("Diastolic Pressure:");

        lblSystolicPressure.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblSystolicPressure.setText("Systolic Pressure:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSystolicPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)
                                .addComponent(txtSystolicPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConfirmAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiastolicPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDiastolicPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDPValid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSPValid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiastolicPressure, txtSystolicPressure});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDPValid, lblSPValid});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(92, 92, 92)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSystolicPressure)
                        .addComponent(txtSystolicPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSPValid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiastolicPressure)
                            .addComponent(txtDiastolicPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDPValid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(btnConfirmAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAddActionPerformed
        // TODO add your handling code here:
        if(txtSystolicPressure.getText().equals("")||txtDiastolicPressure.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Please enter all information!", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            
        encounter.setSystolicPressure(Integer.parseInt(txtSystolicPressure.getText()));
        encounter.setDiastolicPressure(Integer.parseInt(txtDiastolicPressure.getText()));
        encounter.setTime(dateFormat.format(date));
        encounter.setIsNormal();



            

            JOptionPane.showMessageDialog(this, "Encounter added");

        }
    }//GEN-LAST:event_btnConfirmAddActionPerformed

    private void txtSystolicPressureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSystolicPressureKeyReleased
        // only letters
        String regx = "^200|1\\d\\d|[1-9]?\\d$";
        Pattern pattern = Pattern.compile(regx);
        Matcher match = pattern.matcher(txtSystolicPressure.getText());
        if(!match.matches()){
            lblSPValid.setText("Invalid");
        }
        else{
            lblSPValid.setText("OK");
        }
    }//GEN-LAST:event_txtSystolicPressureKeyReleased

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workAreaJPanel.remove(this);
        Component[] componentArray = workAreaJPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewEncounterHistoryJPanel viewEncounterHistoryJPanel = (ViewEncounterHistoryJPanel) component;
        viewEncounterHistoryJPanel.refreshTable();
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDiastolicPressureKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiastolicPressureKeyReleased
        // only numbers
        String regx = "^200|1\\d\\d|[1-9]?\\d$";
        Pattern pattern = Pattern.compile(regx);
        Matcher match = pattern.matcher(txtDiastolicPressure.getText());
        if(!match.matches()){
            lblDPValid.setText("Invalid");
        }
        else{
            lblDPValid.setText("OK");
        }
    }//GEN-LAST:event_txtDiastolicPressureKeyReleased

    private void txtSystolicPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSystolicPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSystolicPressureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmAdd;
    private javax.swing.JLabel lblDPValid;
    private javax.swing.JLabel lblDiastolicPressure;
    private javax.swing.JLabel lblSPValid;
    private javax.swing.JLabel lblSystolicPressure;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtDiastolicPressure;
    private javax.swing.JTextField txtSystolicPressure;
    // End of variables declaration//GEN-END:variables
}
