/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import model.Profile;

/**
 *
 * @author Eva
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPanel
     */
    Profile profile;
    
    public DisplayJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
        displayProfile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplay = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        lblshowPicture = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        lblFaxNum = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSNum = new javax.swing.JLabel();
        lblMRNum = new javax.swing.JLabel();
        lblHPBNum = new javax.swing.JLabel();
        lblLPNum = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblLinkedinLink = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        lblNUId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        txtFaxNum = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSNum = new javax.swing.JTextField();
        txtMRNum = new javax.swing.JTextField();
        txtHPBNum = new javax.swing.JTextField();
        txtLPNum = new javax.swing.JTextField();
        txtDeviceId = new javax.swing.JTextField();
        txtLinkedinLink = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        txtNUId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblDisplay.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        lblDisplay.setForeground(new java.awt.Color(204, 0, 0));
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplay.setText("Diasplay your profile");

        lblPicture.setBackground(new java.awt.Color(255, 255, 255));
        lblPicture.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPicture.setText("Picture:");
        lblPicture.setToolTipText("");

        lblshowPicture.setBackground(new java.awt.Color(204, 204, 204));
        lblshowPicture.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        lblshowPicture.setForeground(new java.awt.Color(153, 153, 153));
        lblshowPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblshowPicture.setText("your picture");
        lblshowPicture.setOpaque(true);

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");
        lblName.setToolTipText("");

        lblZipCode.setBackground(new java.awt.Color(255, 255, 255));
        lblZipCode.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblZipCode.setText("Zip Code:");
        lblZipCode.setToolTipText("");

        lblBirth.setBackground(new java.awt.Color(255, 255, 255));
        lblBirth.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBirth.setText("Birth:");
        lblBirth.setToolTipText("");

        lblPhoneNum.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblPhoneNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNum.setText("Phone Number:");
        lblPhoneNum.setToolTipText("");

        lblFaxNum.setBackground(new java.awt.Color(255, 255, 255));
        lblFaxNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblFaxNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFaxNum.setText("Fax Number:");
        lblFaxNum.setToolTipText("");

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");
        lblEmail.setToolTipText("");

        lblSSNum.setBackground(new java.awt.Color(255, 255, 255));
        lblSSNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblSSNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSSNum.setText("Social Security Number:");
        lblSSNum.setToolTipText("");

        lblMRNum.setBackground(new java.awt.Color(255, 255, 255));
        lblMRNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblMRNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMRNum.setText("Medical Record Number:");
        lblMRNum.setToolTipText("");

        lblHPBNum.setBackground(new java.awt.Color(255, 255, 255));
        lblHPBNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblHPBNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHPBNum.setText("Health Plan Beneficiary Number:");
        lblHPBNum.setToolTipText("");

        lblLPNum.setBackground(new java.awt.Color(255, 255, 255));
        lblLPNum.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblLPNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLPNum.setText(" License Plate Number:");
        lblLPNum.setToolTipText("");

        lblDeviceId.setBackground(new java.awt.Color(255, 255, 255));
        lblDeviceId.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblDeviceId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeviceId.setText("Device Id:");
        lblDeviceId.setToolTipText("");

        lblLinkedinLink.setBackground(new java.awt.Color(255, 255, 255));
        lblLinkedinLink.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblLinkedinLink.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLinkedinLink.setText("Linkedin Link:");
        lblLinkedinLink.setToolTipText("");

        lblIP.setBackground(new java.awt.Color(255, 255, 255));
        lblIP.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblIP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIP.setText("Internet Protocol:");
        lblIP.setToolTipText("");

        lblNUId.setBackground(new java.awt.Color(255, 255, 255));
        lblNUId.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblNUId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNUId.setText("NUID:");
        lblNUId.setToolTipText("");

        txtName.setEditable(false);
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtZipCode.setEditable(false);

        txtBirth.setEditable(false);

        txtPhoneNum.setEditable(false);

        txtFaxNum.setEditable(false);
        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);

        txtSSNum.setEditable(false);

        txtMRNum.setEditable(false);

        txtHPBNum.setEditable(false);

        txtLPNum.setEditable(false);

        txtDeviceId.setEditable(false);

        txtLinkedinLink.setEditable(false);

        txtIP.setEditable(false);

        txtNUId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLinkedinLink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDeviceId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLPNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHPBNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(lblMRNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSSNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFaxNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhoneNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBirth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblZipCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPicture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNUId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtNUId, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtSSNum, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtMRNum, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtHPBNum, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtLPNum, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtDeviceId, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtLinkedinLink, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtIP, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(lblshowPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicture)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblshowPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCode)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBirth)
                    .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNum)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNum)
                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSNum)
                    .addComponent(txtSSNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMRNum)
                    .addComponent(txtMRNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPBNum)
                    .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLPNum)
                    .addComponent(txtLPNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceId)
                    .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedinLink)
                    .addComponent(txtLinkedinLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIP)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNUId)
                    .addComponent(txtNUId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNum;
    private javax.swing.JLabel lblHPBNum;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLPNum;
    private javax.swing.JLabel lblLinkedinLink;
    private javax.swing.JLabel lblMRNum;
    private javax.swing.JLabel lblNUId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblSSNum;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblshowPicture;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNum;
    private javax.swing.JTextField txtHPBNum;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLPNum;
    private javax.swing.JTextField txtLinkedinLink;
    private javax.swing.JTextField txtMRNum;
    private javax.swing.JTextField txtNUId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtSSNum;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() {
        
        
        lblshowPicture.setIcon(profile.getPicIcon());
                
                
         if(profile.getName().equals("no numbers"))
        {
            txtName.setText("no data");
            txtName.setForeground(new Color(153,153,153));
        }
         else txtName.setText(profile.getName());

        
         if(profile.getZipCode().equals("11111 or 11111-1111"))
        {
            txtZipCode.setText("no data");
            txtZipCode.setForeground(new Color(153,153,153));
        }
         else txtZipCode.setText(profile.getZipCode());
        
         
         if(profile.getBirth().equals("mm-dd-yyyy"))
        {
            txtBirth.setText("no data");
            txtBirth.setForeground(new Color(153,153,153));
        }
         else txtBirth.setText(profile.getBirth());
         
         
         if(profile.getPhoneNum().equals("e.g. 111-111-1111"))
        {
            txtPhoneNum.setText("no data");
            txtPhoneNum.setForeground(new Color(153,153,153));
        }
         else txtPhoneNum.setText(profile.getPhoneNum());

       
         if(profile.getFaxNum().equals("+1(11)-111-1111111"))
        {
            txtFaxNum.setText("no data");
            txtFaxNum.setForeground(new Color(153,153,153));
        }
         else txtFaxNum.setText(profile.getFaxNum());
                  
         
         if(profile.getEmail().equals("xxx@xxx.xxx"))
        {
            txtEmail.setText("no data");
            txtEmail.setForeground(new Color(153,153,153));
        }
         else txtEmail.setText(profile.getEmail());
         
         
         if(profile.getSocialSecurityNum().equals("e.g. 111-11-1111"))
        {
            txtSSNum.setText("no data");
            txtSSNum.setForeground(new Color(153,153,153));
        }
         else txtSSNum.setText(profile.getSocialSecurityNum());
         
         
         if(profile.getMedicalRecordNum().equals("MR11111(1)"))
        {
            txtMRNum.setText("no data");
            txtMRNum.setForeground(new Color(153,153,153));
        }
         else txtMRNum.setText(profile.getMedicalRecordNum());         
         
         
         if(profile.getHealthPlanBeneficiaryNum().equals("e.g. 1XX1-X11-XX11"))
        {
            txtHPBNum.setText("no data");
            txtHPBNum.setForeground(new Color(153,153,153));
        }
         else txtHPBNum.setText(profile.getHealthPlanBeneficiaryNum());        
         
         
          if(profile.getLicensePlateNum().equals("X(XX)-X(X)-1(111)"))
        {
            txtLPNum.setText("no data");
            txtLPNum.setForeground(new Color(153,153,153));
        }
         else txtLPNum.setText(profile.getLicensePlateNum());        
         
         
         if(profile.getDeviceId().equals("15 digits(letters or numbers)"))
        {
            txtDeviceId.setText("no data");
            txtDeviceId.setForeground(new Color(153,153,153));
        }
         else txtDeviceId.setText(profile.getDeviceId());        
        
      
         if(profile.getLinkedinLink().equals("http(s)://www.linkedin.com/in/..."))
        {
            txtLinkedinLink.setText("no data");
            txtLinkedinLink.setForeground(new Color(153,153,153));
        }
         else txtLinkedinLink.setText(profile.getLinkedinLink());
         
         
         if(profile.getInternetProtocol().equals("0~255.0~255.0~255.0~255"))
        {
            txtIP.setText("no data");
            txtIP.setForeground(new Color(153,153,153));
        }
         else txtIP.setText(profile.getInternetProtocol());
         
         
         if(profile.getNuid().equals("e.g. 111111111"))
        {
            txtNUId.setText("no data");
            txtNUId.setForeground(new Color(153,153,153));
        }
         else txtNUId.setText(profile.getNuid());         
        
     
    }
}
