/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Ecosystem.DB4OUtil.DB4OUtil;
import Ecosystem.FilmFactorySystem;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkOrangeIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkContrastIJTheme;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;
import ui.Login.LoginSystemAdminJPanel;

/**
 *
 * @author Eva
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private FilmFactorySystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public MainJFrame() {
        initComponents();
        setSize(750, 600);
        this.setResizable(false);
        system = dB4OUtil.retrieveSystem();
        initLoginScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        menuArea = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPanel.setDividerLocation(40);
        SplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuArea.setMinimumSize(new java.awt.Dimension(50, 50));
        menuArea.setName(""); // NOI18N
        menuArea.setPreferredSize(new java.awt.Dimension(748, 30));

        btnLogout.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(83, 30));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Film Factory");

        javax.swing.GroupLayout menuAreaLayout = new javax.swing.GroupLayout(menuArea);
        menuArea.setLayout(menuAreaLayout);
        menuAreaLayout.setHorizontalGroup(
            menuAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAreaLayout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menuAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
        );
        menuAreaLayout.setVerticalGroup(
            menuAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAreaLayout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(menuAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuAreaLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SplitPanel.setTopComponent(menuArea);

        workArea.setLayout(new java.awt.CardLayout());
        SplitPanel.setRightComponent(workArea);

        getContentPane().add(SplitPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        workArea.removeAll();
        JPanel rcjp = new RolesChooseJPanel(workArea, menuArea,system);
        workArea.add("LoginScreen", rcjp);
        CardLayout crdLyt = (CardLayout) workArea.getLayout();
        crdLyt.next(workArea);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
//            UIManager.setLookAndFeel(new FlatDarculaLaf());
               FlatGradiantoNatureGreenIJTheme.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menuArea;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    private void initLoginScreen() {

        btnLogout.setVisible(true);
        JPanel rcjp = new RolesChooseJPanel(workArea, menuArea,system);
        workArea.add("LoginScreen", rcjp);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }


}
