/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdmin;

import Ecosystem.FilmFactorySystem;
import Ecosystem.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eva
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel workArea;
    FilmFactorySystem system;
    /**
     * Creates new form SystemAdminWork
     */
    public SystemAdminWorkAreaJPanel(JPanel workArea, FilmFactorySystem system) {
        initComponents();
        this.workArea= workArea;
        this.system = system;
        sVGImage1.setSvgImage("UIDesign/undraw_file_manager_j-85-s.svg", 230,160);
        setSize(750, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageCinemaAdmin = new javax.swing.JButton();
        btnManageFilmAdmin = new javax.swing.JButton();
        btnManageCustomer = new javax.swing.JButton();
        sVGImage1 = new UIDesign.SVGImage();
        btnViewDataModule = new javax.swing.JButton();

        setBackground(new java.awt.Color(10, 10, 10));

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("System Admin Work Area");

        btnManageCinemaAdmin.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnManageCinemaAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCinemaAdmin.setText("Manage PlatformAdmin");
        btnManageCinemaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCinemaAdminActionPerformed(evt);
            }
        });

        btnManageFilmAdmin.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnManageFilmAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFilmAdmin.setText("Manage FilmAdmin");
        btnManageFilmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFilmAdminActionPerformed(evt);
            }
        });

        btnManageCustomer.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnManageCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCustomer.setText("Manage Customers");
        btnManageCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomerActionPerformed(evt);
            }
        });

        btnViewDataModule.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnViewDataModule.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDataModule.setText("View Data Module");
        btnViewDataModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataModuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(sVGImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageCinemaAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageFilmAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewDataModule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)))
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sVGImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnManageCinemaAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnManageFilmAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnManageCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnViewDataModule)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageCustomer, btnViewDataModule});

    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomerActionPerformed
        
        ManageCustomerJPanel mcsjp = new ManageCustomerJPanel(workArea, system);
        workArea.add("ManageCustomerJPanel", mcsjp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageCustomerActionPerformed

    private void btnManageCinemaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCinemaAdminActionPerformed
        for(Network network: system.getNetworkList()) {
        }
        ManageCinemaAdminJPanel mcajp = new ManageCinemaAdminJPanel(workArea, system);
        workArea.add("ManageCinemaAdminJPanel", mcajp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageCinemaAdminActionPerformed

    private void btnManageFilmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFilmAdminActionPerformed
        ManageFilmAdminJPanel mfajp = new ManageFilmAdminJPanel(workArea, system);
        workArea.add("ManageFilmAdminJPanel", mfajp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageFilmAdminActionPerformed

    private void btnViewDataModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataModuleActionPerformed
        ViewDataModuleJPanel vdmjp = new ViewDataModuleJPanel(workArea, system);
        workArea.add("ViewDataModuleJPanel", vdmjp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewDataModuleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCinemaAdmin;
    private javax.swing.JButton btnManageCustomer;
    private javax.swing.JButton btnManageFilmAdmin;
    private javax.swing.JButton btnViewDataModule;
    private javax.swing.JLabel lblTitle;
    private UIDesign.SVGImage sVGImage1;
    // End of variables declaration//GEN-END:variables
}
